Repository Kentico/kontent-delivery-sdk-js, pull requests merged in 2019-02, with the labels that each got.

#100 internal - test removes line
  packages/delivery/demo/umd-promise/index.html
Labels: internal

#102 Basic CM Api documentation
  packages/content-management/README.md
  packages/content-management/demo/cm-jsdelivr.html
  packages/content-management/demo/cm-unpkg.html
Labels: documentation

#103 Updates main readme
  packages/content-management/README.md
  readme.md
Labels: documentation

#105 Uses jsdelivr for badges
  readme.md
Labels: documentation

#106 Fixes typo and improves retryAttempts description
  packages/content-management/README.md
Labels: documentation

#111 Feat image resolver
  packages/delivery/DOCS.md
  packages/delivery/lib/data-contracts/item-contracts.ts
  packages/delivery/lib/fields/field-contracts.ts
  packages/delivery/lib/fields/field-types.ts
  packages/delivery/lib/images/image-url-builder.ts
  packages/delivery/lib/interfaces/item/iitem-query.config.ts
  packages/delivery/lib/interfaces/item/index.ts
  packages/delivery/lib/interfaces/item/irich-text-resolver-result.ts
  packages/delivery/lib/mappers/field.mapper.ts
  packages/delivery/lib/models/common/parameters.ts
  packages/delivery/lib/models/item/content-item.class.ts
  packages/delivery/lib/models/item/image.class.ts
  packages/delivery/lib/models/item/index.ts
  packages/delivery/lib/models/item/link.class.ts
  packages/delivery/lib/parser/adapters/browser-rich-text.parser.ts
  packages/delivery/lib/parser/adapters/parse5-rich-text.parser.ts
  packages/delivery/lib/parser/parse-models.ts
  packages/delivery/lib/resolvers/rich-text.resolver.ts
  packages/delivery/lib/resolvers/url-slug.resolver.ts
  packages/delivery/test-browser/isolated-tests/fields/rich-text-html-link.spec.ts
  packages/delivery/test-browser/isolated-tests/fields/rich-text-images.spec.ts
  packages/delivery/test-browser/isolated-tests/fields/rich-text.spec.ts
  packages/delivery/test-browser/isolated-tests/images/image-url-builder.spec.ts
  packages/delivery/test-browser/live-tests/item/live-item.spec.ts
  packages/delivery/test-node/rich-text/live-rich-text-images.js
  packages/delivery/test-node/rich-text/live-rich-text-links.js
Labels: documentation, enhancement

#112 Link test http service mention to the docs
  packages/content-management/README.md
  packages/core/README.md
  packages/delivery/DOCS.md
  packages/delivery/README.md
Labels: documentation

#115 Fixes browser's UMD library bundle global property, handles field name collisions and uses dedicated types for resolvers
  packages/delivery/DOCS.md
  packages/delivery/karma.conf.js
  packages/delivery/lib/config/default-collision-resolver.ts
  packages/delivery/lib/config/delivery-client.config.ts
  packages/delivery/lib/config/index.ts
  packages/delivery/lib/data-contracts/item-contracts.ts
  packages/delivery/lib/fields/field-decorators.ts
  packages/delivery/lib/interfaces/item/iitem-query.config.ts
  packages/delivery/lib/mappers/field.mapper.ts
  packages/delivery/lib/models/item/content-item.class.ts
  packages/delivery/lib/models/item/index.ts
  packages/delivery/lib/models/item/item-resolvers.ts
  packages/delivery/lib/models/item/type-resolver.class.ts
  packages/delivery/lib/resolvers/rich-text.resolver.ts
  packages/delivery/lib/resolvers/strongly-type.resolver.ts
  packages/delivery/lib/resolvers/url-slug.resolver.ts
  packages/delivery/test-browser/isolated-tests/resolvers/property-resolver.spec.ts
  packages/delivery/test-browser/isolated-tests/resolvers/url-slug-resolver.spec.ts
  packages/delivery/test-browser/new-tests-refactoring/fields/collission-field-names.spec.json
  packages/delivery/test-browser/new-tests-refactoring/fields/collission-field-names.spec.ts
  packages/delivery/webpack.browser.config.js
Labels: bug, enhancement

#116 Uses jsdelivr CDN in HTML examples
  packages/delivery/DOCS.md
  packages/delivery/README.md
Labels: documentation

#117 Extends collisionResolver docs
  packages/delivery/DOCS.md
Labels: documentation

#119 Fixes an issue where a content item would be resolved multiple times in certain scenarios
  packages/delivery/lib/mappers/field.mapper.ts
  packages/delivery/lib/mappers/item.mapper.ts
  packages/delivery/test-browser/live-tests/item/live-item.spec.ts
Labels: bug

#120 Adds 'linkedItems' property holding all resolved linked items in a flat structure
  packages/delivery/lib/mappers/field.mapper.ts
  packages/delivery/lib/mappers/item.mapper.ts
  packages/delivery/lib/mappers/response.mapper.ts
  packages/delivery/lib/models/item/responses.ts
  packages/delivery/test-browser/isolated-tests/response/responses.spec.ts
  packages/delivery/test-browser/live-tests/item/live-item-base-linked-items.spec.ts
  packages/delivery/test-browser/live-tests/item/live-item.spec.ts
  packages/delivery/test-browser/live-tests/items/live-items.spec.ts
Labels: enhancement

#121 Adds support for retrying Promises
  packages/core/karma.conf.js
  packages/core/lib/http/http.service.ts
  packages/core/lib/http/ihttp.service.ts
  packages/core/lib/http/index.ts
  packages/core/lib/http/retry-service.ts
  packages/core/lib/http/retry-strategy.ts
  packages/core/lib/http/test-http.service.ts
  packages/core/lib/sdk-info.generated.ts
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/test-browser/observable/delayed-http-execution.spec.ts
  packages/core/test-browser/retry-strategy-observable/retry-isolated-do-not-retry.spec.ts
  packages/core/test-browser/retry-strategy-observable/retry-isolated-do-retry.spec.ts
  packages/core/test-browser/retry-strategy-promise/retry-isolated-promise-do-not-retry.spec.ts
  packages/core/test-browser/retry-strategy-promise/retry-isolated-promise-do-retry.spec.ts
Labels: enhancement

#123 Fix response mapping if request is successful for the first time
  packages/core/lib/http/http.service.ts
  packages/core/lib/sdk-info.generated.ts
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/test-browser/observable/subscribe-http-execution.spec.ts
  packages/core/test-browser/promise/promise-execution.spec.ts
Labels: bug

#125 Fix autogenerated version name
  packages/delivery/CHANGELOG.md
Labels: documentation

#126 Stores current retry attempt to ensure correct timeout is used for retrying additional requests
  packages/core/lib/http/http.service.ts
  packages/core/lib/http/ihttp.service.ts
  packages/core/lib/sdk-info.generated.ts
  packages/core/package-lock.json
  packages/core/package.json
Labels: bug

#127 Updates to kentico-cloud-core@1.4.3 (fixes timeouts when retrying Promise requests)
  docs/delivery/modules/_sdk_info_generated_.html
  packages/delivery/lib/sdk-info.generated.ts
  packages/delivery/lib/services/base-delivery-query.service.ts
  packages/delivery/package-lock.json
  packages/delivery/package.json
Labels: bug

#128 Adds ability to configure error status codes of request that should be retried
  packages/delivery/DOCS.md
  packages/delivery/lib/config/delivery-client.config.ts
  packages/delivery/lib/services/base-delivery-query.service.ts
  packages/delivery/test-browser/live-tests/retry/retry-isolated-promise.do-retry.spec.ts
  packages/delivery/test-browser/setup/context.ts
  packages/delivery/test-browser/setup/setup.ts
Labels: enhancement

#129 Fixes HTTP request type for update asset & upsert asset queries
  packages/content-management/lib/services/content-management-query-service.class.ts
Labels: bug

#131 Updates kentico-cloud-core dependency to 1.4.3
  packages/content-management/package.json
Labels: enhancement

#132 Adds ability to configure status codes of requests that should be retried and adds support for retrying Promises
  packages/content-management/README.md
  packages/content-management/karma-travis.conf.js
  packages/content-management/karma.conf.js
  packages/content-management/lib/config/icontent-management-client-config.interface.ts
  packages/content-management/lib/queries/base-query.ts
  packages/content-management/lib/services/base-content-management-service.class.ts
Labels: enhancement
