Repository Kentico/kontent-delivery-sdk-js, pull requests merged in 2019-03, with the labels that each got.

#138 Fixes an issue when mapper would throw Stackoverflow exception when child item contained linked reference to parent
  docs/delivery/assets/js/search.js
  docs/delivery/classes/_mappers_field_mapper_.fieldmapper.html
  docs/delivery/classes/_mappers_item_mapper_.itemmapper.html
  docs/delivery/classes/_mappers_taxonomy_mapper_.taxonomymapper.html
  docs/delivery/classes/_mappers_type_mapper_.typemapper.html
  docs/delivery/classes/_models_common_filters_.filters.allfilter.html
  docs/delivery/classes/_models_common_filters_.filters.anyfilter.html
  docs/delivery/classes/_models_common_filters_.filters.containsfilter.html
  docs/delivery/classes/_models_common_filters_.filters.equalsfilter.html
  docs/delivery/interfaces/_mappers_field_mapper_.imapfieldsresult.html
  docs/delivery/interfaces/_mappers_item_mapper_.mapitemresult.html
  docs/delivery/interfaces/_mappers_item_mapper_.mapitemsresult.html
  docs/delivery/modules/_mappers_field_mapper_.html
  docs/delivery/modules/_mappers_item_mapper_.html
  docs/delivery/modules/_mappers_type_mapper_.html
  docs/delivery/modules/_models_common_filters_.filters.html
  docs/delivery/modules/_models_common_filters_.html
  docs/delivery/modules/_sdk_info_generated_.html
  package-lock.json
  package.json
  packages/content-management/package-lock.json
  packages/content-management/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/delivery/lib/mappers/field.mapper.ts
  packages/delivery/lib/mappers/item.mapper.ts
  packages/delivery/lib/sdk-info.generated.ts
  packages/delivery/package-lock.json
  packages/delivery/package.json
  packages/delivery/test-browser/isolated-tests/services/field-mapper.spec.ts
  packages/model-generator/package-lock.json
  packages/model-generator/package.json
Labels: enhancement

#140 Adds 'withParameters' query method
  packages/delivery/lib/models/common/parameters.ts
  packages/delivery/lib/query/common/base-query.class.ts
Labels: enhancement

#146 SEX-872 - Fix Insecure Protocol
  docs/content-management/index.html
Labels: enhancement

#149 Adds external_id, taxonomy_group and snippet to content type elementmodel, updates docs and package version
  docs/content-management/assets/js/search.js
  docs/content-management/interfaces/_models_content_types_content_type_models_.contenttypemodels.iaddcontenttypecustomelementdata.html
  docs/content-management/interfaces/_models_content_types_content_type_models_.contenttypemodels.iaddcontenttypeelementdata.html
  docs/content-management/interfaces/_models_content_types_content_type_models_.contenttypemodels.iaddcontenttypeelementdependsondata.html
  docs/content-management/interfaces/_models_content_types_content_type_models_.contenttypemodels.iaddcontenttypeelementmultiplechoiceelementoptionsdata.html
  docs/content-management/modules/_sdk_info_generated_.html
  packages/content-management/lib/models/content-types/content-type.models.ts
  packages/content-management/lib/sdk-info.generated.ts
  packages/content-management/package-lock.json
  packages/content-management/package.json
Labels: enhancement

#151 Preserves original error when mapping to CloudError
  packages/core/lib/error-handling/cloud-error.ts
  packages/core/lib/error-handling/map-cloud-error.ts
Labels: enhancement

#152 Core changelog and version update
  packages/core/CHANGELOG.md
  packages/core/lib/sdk-info.generated.ts
  packages/core/package-lock.json
  packages/core/package.json
Labels: internal

#153 Update to kentico-cloud-core@1.4.4
  docs/delivery/modules/_sdk_info_generated_.html
  packages/content-management/package.json
  packages/delivery/lib/sdk-info.generated.ts
  packages/delivery/package-lock.json
  packages/delivery/package.json
Labels: enhancement

#154 Uses Content Management specific error and sets validation errors where applicable
  packages/content-management/lib/contracts/shared-contracts.ts
  packages/content-management/lib/models/shared/shared-models.ts
  packages/content-management/lib/services/base-content-management-service.class.ts
  packages/content-management/package.json
  packages/content-management/test-browser/errors/cm-errors.spec.ts
  packages/content-management/test-browser/fake-responses/fake-error.json
Labels: enhancement

#156 Updates dev dependencies and some scripts (+ preparation for circle ci)
  .circleci/config.yml
  lerna-debug.log
  package-lock.json
  package.json
  packages/angular-http-service/package-lock.json
  packages/content-management/karma-travis.conf.js
  packages/content-management/package-lock.json
  packages/content-management/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/delivery/package-lock.json
  packages/delivery/package.json
  packages/model-generator/package-lock.json
  packages/model-generator/package.json
Labels: internal

#157 Switch to 'karma-typescript' and 'karma-typescript-es6-transform' for better performance, adds CircleCI badges, fixes incorrect import path in CM base service
  packages/content-management/README.md
  packages/content-management/karma-travis.conf.js
  packages/content-management/karma.conf.js
  packages/content-management/lib/services/base-content-management-service.class.ts
  packages/content-management/package-lock.json
  packages/content-management/package.json
  packages/core/README.md
  packages/delivery/README.md
  packages/delivery/karma-travis.conf.js
  packages/delivery/karma.conf.js
  packages/delivery/package-lock.json
  packages/delivery/package.json
  readme.md
Labels: bug, internal
